# Generated by Django 4.2 on 2025-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional)', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
