# Generated by Django 4.2 on 2025-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='accessibility_needs',
            field=models.JSONField(blank=True, default=list, help_text='Accessibility requirements'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='accommodation_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Preferred accommodation types'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='activity_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Preferred activities during travel'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('budget', 'Budget-friendly'), ('moderate', 'Moderate'), ('luxury', 'Luxury'), ('premium', 'Premium')], help_text='Preferred budget range for travel', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Dietary restrictions or preferences'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='List of travel interests'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='language_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Preferred languages for communication'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Notification preferences (email, sms, push)'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_destinations',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred destinations or regions'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_group_size',
            field=models.CharField(blank=True, choices=[('1', 'Solo (1 person)'), ('2', 'Couple (2 people)'), ('3-5', 'Small group (3-5 people)'), ('6-10', 'Medium group (6-10 people)'), ('10+', 'Large group (10+ people)')], help_text='Preferred group size for travel', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='transportation_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Preferred transportation methods'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='travel_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Never traveled'), ('rarely', 'Rarely (1-2 times per year)'), ('occasionally', 'Occasionally (3-5 times per year)'), ('frequently', 'Frequently (6-10 times per year)'), ('very_frequently', 'Very frequently (10+ times per year)')], help_text='How often do you travel', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('solo', 'Solo Travel'), ('couple', 'Couple Travel'), ('family', 'Family Travel'), ('group', 'Group Travel'), ('business', 'Business Travel'), ('backpacker', 'Backpacker')], help_text='Preferred travel style', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
