# Generated by Django 4.2 on 2025-08-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpreferences_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='dietary_preferences',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='language_preferences',
        ),
    ]
