# Generated by Django 4.2 on 2025-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_commented_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='accessibility_needs',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='accommodation_preferences',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='activity_preferences',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferred_destinations',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferred_group_size',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='transportation_preferences',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='travel_frequency',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('solo', 'Solo Travel'), ('couple', 'Couple Travel'), ('family', 'Family Travel'), ('group', 'Group Travel')], help_text='Preferred travel style', max_length=20, null=True),
        ),
    ]
