# Generated by Django 4.2 on 2025-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_simplify_preferences_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='activity_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Preferred activities during travel'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_destinations',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred destinations or regions'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_group_size',
            field=models.CharField(blank=True, choices=[('1', 'Solo (1 person)'), ('2', 'Couple (2 people)'), ('3-5', 'Small group (3-5 people)'), ('6-10', 'Medium group (6-10 people)'), ('10+', 'Large group (10+ people)')], help_text='Preferred group size for travel', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='transportation_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Preferred transportation methods'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='travel_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Never traveled'), ('rarely', 'Rarely (1-2 times per year)'), ('occasionally', 'Occasionally (3-5 times per year)'), ('frequently', 'Frequently (6-10 times per year)'), ('very_frequently', 'Very frequently (10+ times per year)')], help_text='How often do you travel', max_length=20, null=True),
        ),
    ]
