# Generated by Django 4.2 on 2025-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_restore_preferences_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='User verification status'),
        ),
    ]
