# Generated by Django 4.2 on 2025-08-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardpayment_mpesapayment_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='mpesa_callback_url',
            field=models.URLField(blank=True, help_text='M-Pesa callback URL for webhooks'),
        ),
    ]
