# Generated by Django 4.2 on 2025-08-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscriptionplan_verificationrequest_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_completed', 'Payment Completed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_info', 'Requires More Information')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card')], default='mpesa', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mpesa_result_desc', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('verification_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.verificationrequest')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
