# Generated by Django 4.2 on 2025-08-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_eventbooking_created_at_eventbooking_payment_date_and_more'),
        ('core', '0005_alter_verificationrequest_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='listings.agency'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='duration_years',
            field=models.PositiveIntegerField(default=1, help_text='Number of years for verification'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='listings.place'),
        ),
    ]
