# Generated by Django 4.2 on 2025-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aichatinteraction_aiinsightsreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='mpesa_initiator_name',
            field=models.CharField(blank=True, help_text='M-Pesa initiator name for API calls', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='mpesa_security_credential',
            field=models.CharField(blank=True, help_text='M-Pesa security credential for API calls', max_length=500),
        ),
    ]
