# Generated by Django 4.2 on 2025-08-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_paymentsettings_mpesa_initiator_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100)),
                ('chat_type', models.CharField(choices=[('place', 'Place Chat'), ('agency', 'Agency Chat')], max_length=20)),
                ('content_id', models.PositiveIntegerField(help_text='ID of the place or agency')),
                ('user_question', models.TextField(help_text="User's question")),
                ('ai_response', models.TextField(help_text="AI's response")),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Number of tokens used')),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Response time in milliseconds')),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', help_text='AI model used', max_length=50)),
                ('user_agent', models.TextField(blank=True, help_text="User's browser/device information")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['chat_type', 'content_id'], name='core_chathi_chat_ty_8d43ac_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', 'created_at'], name='core_chathi_user_id_0859be_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['session_id', 'created_at'], name='core_chathi_session_2883f2_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['created_at'], name='core_chathi_created_53feaa_idx'),
        ),
    ]
