# Generated by Django 4.2 on 2025-08-26 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_placeorder_placestaff_placeorderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_chathistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('place', 'Place Chat'), ('agency', 'Agency Chat')], max_length=10)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for analytics', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string for analytics')),
                ('question', models.TextField()),
                ('question_tokens', models.PositiveIntegerField(default=0, help_text='Number of tokens in the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether the user was anonymous')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_questions', to='listings.agency')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_questions', to='listings.place')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Question',
                'verbose_name_plural': 'Chat Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('response_tokens', models.PositiveIntegerField(default=0, help_text='Number of tokens in the response')),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', help_text='AI model used for response', max_length=50)),
                ('model_version', models.CharField(blank=True, help_text='Specific model version', max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Response time in milliseconds')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total tokens used (question + response)')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost in USD for this response', max_digits=10)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-1)', max_digits=3, null=True)),
                ('user_feedback', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('not_rated', 'Not Rated')], default='not_rated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='core.chatquestion')),
            ],
            options={
                'verbose_name': 'Chat Response',
                'verbose_name_plural': 'Chat Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.AddIndex(
            model_name='chatresponse',
            index=models.Index(fields=['ai_model', 'created_at'], name='core_chatre_ai_mode_27d787_idx'),
        ),
        migrations.AddIndex(
            model_name='chatresponse',
            index=models.Index(fields=['user_feedback', 'created_at'], name='core_chatre_user_fe_1cc767_idx'),
        ),
        migrations.AddIndex(
            model_name='chatresponse',
            index=models.Index(fields=['response_time_ms', 'created_at'], name='core_chatre_respons_c0dfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['chat_type', 'created_at'], name='core_chatqu_chat_ty_f04e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['place', 'created_at'], name='core_chatqu_place_i_c00017_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['agency', 'created_at'], name='core_chatqu_agency__c19ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['user', 'created_at'], name='core_chatqu_user_id_d237e1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquestion',
            index=models.Index(fields=['session_id', 'created_at'], name='core_chatqu_session_0c6505_idx'),
        ),
    ]
