# Generated by Django 5.2.5 on 2025-08-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatquestion_chatresponse_delete_chathistory_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscriptionplan',
            name='core_subscr_plan_ty_a47c39_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionplan',
            name='core_subscr_is_popu_6f6b57_idx',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='date_builder_priority',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_agencies',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_ai_chats_per_month',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_insights_reports',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_places',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='target_type',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year'), (730, '2 Years')], default=365),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
