# Generated by Django 5.2.5 on 2025-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_subscriptionplan_core_subscr_plan_ty_a47c39_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='OpenAI API key', max_length=200)),
            ],
            options={
                'verbose_name': 'OpenAI API Key',
                'verbose_name_plural': 'OpenAI API Keys',
            },
        ),
    ]
