# Generated by Django 5.2.5 on 2025-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_openaiapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiapikey',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
