# Generated by Django 4.2 on 2025-08-06 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_groups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_groups', to='listings.place'),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='travel_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='listings.placecategory'),
        ),
        migrations.AddField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
