# Generated by Django 4.2.13 on 2025-08-06 15:48

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelgroup',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='travelgroup',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='travelgroup',
            name='start_date',
        ),
        migrations.AddField(
            model_name='place',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Main profile picture for the place', null=True, upload_to=listings.models.place_profile_picture_path),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='group_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('one-time', 'One-time')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='objective',
            field=models.CharField(choices=[('explore', 'Explore'), ('connect', 'Connect'), ('experience', 'Experience')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.place_image_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='listings.place')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
