# Generated by Django 4.2.13 on 2025-08-06 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_remove_travelgroup_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('expert', 'Expert')], default='moderate', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('included_services', models.TextField(blank=True, help_text="What's included in the tour price", null=True)),
                ('excluded_services', models.TextField(blank=True, help_text="What's not included in the tour price", null=True)),
                ('requirements', models.TextField(blank=True, help_text='Requirements for participants', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tours_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tours', to='listings.place')),
                ('travel_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_tours', to='listings.travelgroup')),
            ],
        ),
    ]
