# Generated by Django 4.2 on 2025-08-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0004_grouptours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptours',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='grouptours',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='grouptours',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grouptours',
            name='max_age',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='grouptours',
            name='min_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grouptours',
            name='min_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='grouptours',
            name='destination',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tour', 'Tour'), ('activity', 'Activity'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('included_services', models.TextField(blank=True, help_text="What's included in the tour price", null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('travel_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.travelgroup')),
            ],
        ),
        migrations.AddField(
            model_name='grouptours',
            name='destination',
            field=models.ManyToManyField(related_name='destinations', to='listings.place'),
        ),
    ]
