# Generated by Django 4.2.13 on 2025-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptours',
            name='couple_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
