# Generated by Django 4.2.13 on 2025-08-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_grouptours_couple_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptours',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.agency'),
        ),
    ]
