# Generated by Django 4.2 on 2025-08-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_event_bookmarks_event_likes_grouptours_bookmarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature name (e.g., Swimming Pool, Playground)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the feature', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this feature', max_digits=10)),
                ('duration', models.CharField(blank=True, help_text='Duration (e.g., 2 hours, Full day)', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Feature image', null=True, upload_to='features/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='listings.place')),
            ],
            options={
                'verbose_name_plural': 'Features',
                'ordering': ['-created_at'],
            },
        ),
    ]
