# Generated by Django 4.2.13 on 2025-08-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Main Dishes, Beverages)', max_length=100)),
                ('category_type', models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('side_dish', 'Side Dish'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('alcoholic', 'Alcoholic'), ('non_alcoholic', 'Non-Alcoholic'), ('hot_drinks', 'Hot Drinks'), ('cold_drinks', 'Cold Drinks'), ('other', 'Other')], default='food', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji for the category', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='listings.place')),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('place', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Menu item name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the menu item')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price', max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price if applicable', max_digits=10, null=True)),
                ('is_discounted', models.BooleanField(default=False, help_text='Whether this item is currently discounted')),
                ('ingredients', models.TextField(blank=True, help_text='List of ingredients', null=True)),
                ('allergens', models.TextField(blank=True, help_text='Allergen information', null=True)),
                ('spice_level', models.CharField(blank=True, choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra_hot', 'Extra Hot'), ('customizable', 'Customizable')], max_length=20, null=True)),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('serving_size', models.CharField(blank=True, help_text='Serving size (e.g., 250g, 1 cup)', max_length=100, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('out_of_stock', 'Out of Stock'), ('seasonal', 'Seasonal'), ('daily_special', 'Daily Special')], default='available', max_length=20)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=False)),
                ('is_kosher', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Menu item image', null=True, upload_to='menu_items/')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured item')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='listings.menucategory')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='listings.place')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category__order', 'order', 'name'],
                'unique_together': {('place', 'category', 'name')},
            },
        ),
    ]
