# Generated by Django 4.2 on 2025-08-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_agencyrating_placerating_ratinghelpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_picture',
            field=models.ImageField(blank=True, help_text='Main photo for the event (recommended size: 800x600px)', null=True, upload_to='events/display_pictures/'),
        ),
        migrations.AddField(
            model_name='grouptours',
            name='display_picture',
            field=models.ImageField(blank=True, help_text='Main photo for the tour (recommended size: 800x600px)', null=True, upload_to='tours/display_pictures/'),
        ),
    ]
