# Generated by Django 4.2 on 2025-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_event_display_picture_grouptours_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptours',
            name='to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grouptours',
            name='destination',
            field=models.ManyToManyField(blank=True, null=True, related_name='destinations', to='listings.place'),
        ),
    ]
