# Generated by Django 4.2.13 on 2025-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_grouptours_to_alter_grouptours_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptours',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
