# Generated by Django 4.2 on 2025-08-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_grouptours_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('transport', 'Transport Services'), ('tour_guide', 'Tour Guide Services'), ('accommodation', 'Accommodation Services'), ('booking', 'Booking Services'), ('custom_tours', 'Custom Tours'), ('adventure', 'Adventure Activities'), ('cultural', 'Cultural Experiences'), ('wildlife', 'Wildlife Safaris'), ('beach', 'Beach & Coastal Tours'), ('mountain', 'Mountain & Hiking Tours'), ('city_tours', 'City Tours'), ('food_tours', 'Food & Culinary Tours'), ('photography', 'Photography Tours'), ('luxury', 'Luxury Travel Services'), ('budget', 'Budget Travel Services'), ('corporate', 'Corporate Travel Services'), ('events', 'Event Planning'), ('transportation', 'Transportation & Logistics'), ('insurance', 'Travel Insurance'), ('visa', 'Visa & Documentation'), ('other', 'Other Services')], max_length=50)),
                ('name', models.CharField(help_text='Specific name for this service', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('unavailable', 'Currently Unavailable'), ('seasonal', 'Seasonal Service')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured service')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price for this service', max_digits=10, null=True)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price range', max_digits=10, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price range', max_digits=10, null=True)),
                ('pricing_model', models.CharField(blank=True, help_text='e.g., Per Person, Per Day, Fixed Rate', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g., 2 hours, Full day, 3 days', max_length=100, null=True)),
                ('group_size_min', models.PositiveIntegerField(blank=True, help_text='Minimum group size', null=True)),
                ('group_size_max', models.PositiveIntegerField(blank=True, help_text='Maximum group size', null=True)),
                ('service_image', models.ImageField(blank=True, help_text='Image representing this service', null=True, upload_to='agencies/services/')),
                ('requirements', models.TextField(blank=True, help_text='Requirements for customers', null=True)),
                ('included_items', models.TextField(blank=True, help_text="What's included in the service", null=True)),
                ('excluded_items', models.TextField(blank=True, help_text="What's not included", null=True)),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation and refund policy', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='listings.agency')),
            ],
            options={
                'verbose_name_plural': 'Agency Services',
                'ordering': ['-is_featured', 'service_type', 'name'],
                'unique_together': {('agency', 'service_type', 'name')},
            },
        ),
    ]
