# Generated by Django 4.2 on 2025-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_agencyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='verified',
            field=models.BooleanField(default=False, help_text='Agency verification status'),
        ),
        migrations.AddField(
            model_name='place',
            name='verified',
            field=models.BooleanField(default=False, help_text='Place verification status'),
        ),
    ]
