# Generated by Django 4.2 on 2025-08-14 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_agency_verified_place_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
