# Generated by Django 4.2 on 2025-08-15 07:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0018_eventbooking_created_at_eventbooking_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Unique payment reference', max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, help_text='External payment provider reference', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Payment description or notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='listings.tourbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour Booking Payment',
                'verbose_name_plural': 'Tour Booking Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['payment_reference'], name='listings_to_payment_5432a5_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['external_reference'], name='listings_to_externa_cf6b92_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['payment_status'], name='listings_to_payment_8c5fde_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['user', 'created_at'], name='listings_to_user_id_9474a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['booking', 'created_at'], name='listings_to_booking_a98f41_idx'),
        ),
    ]
