# Generated by Django 4.2 on 2025-08-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_verificationrequest_agency_and_more'),
        ('listings', '0019_tourbookingpayment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tourbookingpayment',
            name='listings_to_externa_cf6b92_idx',
        ),
        migrations.AddField(
            model_name='tourbookingpayment',
            name='card_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_booking_payments', to='core.cardpayment'),
        ),
        migrations.AddField(
            model_name='tourbookingpayment',
            name='mpesa_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_booking_payments', to='core.mpesapayment'),
        ),
        migrations.AddField(
            model_name='tourbookingpayment',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_booking_payments', to='core.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='tourbookingpayment',
            name='description',
            field=models.TextField(blank=True, help_text='Payment description'),
        ),
        migrations.AlterField(
            model_name='tourbookingpayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tourbookingpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_booking_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tourbooking',
            unique_together={('user', 'tour')},
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['payment_transaction'], name='listings_to_payment_b9914d_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['mpesa_payment'], name='listings_to_mpesa_p_7a9245_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbookingpayment',
            index=models.Index(fields=['card_payment'], name='listings_to_card_pa_5a8db7_idx'),
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='payment_status',
        ),
    ]
