# Generated by Django 4.2 on 2025-08-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_remove_tourbookingpayment_listings_to_externa_cf6b92_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_gallery_images', to='listings.place')),
            ],
            options={
                'verbose_name': 'Place Gallery Image',
                'verbose_name_plural': 'Place Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agencies/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='listings.agency')),
            ],
            options={
                'verbose_name': 'Agency Gallery Image',
                'verbose_name_plural': 'Agency Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
