# Generated by Django 4.2 on 2025-08-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_placegallery_agencygallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications and awards'),
        ),
        migrations.AddField(
            model_name='agency',
            name='group_size_range',
            field=models.CharField(blank=True, help_text="Group size range (e.g., '1-10', '10-50', '50+')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=['English'], help_text='Languages spoken by staff'),
        ),
        migrations.AddField(
            model_name='agency',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours for each day of the week'),
        ),
        migrations.AddField(
            model_name='agency',
            name='price_range',
            field=models.CharField(choices=[('budget', 'Budget'), ('mid_range', 'Mid-Range'), ('premium', 'Premium'), ('luxury', 'Luxury')], default='mid_range', help_text='Price range of services offered', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text="List of specialties (e.g., ['adventure', 'cultural', 'wildlife', 'beach'])"),
        ),
        migrations.AddField(
            model_name='place',
            name='accessibility_features',
            field=models.JSONField(blank=True, default=list, help_text="List of accessibility features (e.g., ['wheelchair_accessible', 'braille_signs'])"),
        ),
        migrations.AddField(
            model_name='place',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text="List of available amenities (e.g., ['parking', 'restrooms', 'wifi'])"),
        ),
        migrations.AddField(
            model_name='place',
            name='average_visit_duration',
            field=models.PositiveIntegerField(default=2, help_text='Average time spent at this place (in hours)'),
        ),
        migrations.AddField(
            model_name='place',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text="Best time of year to visit (e.g., 'June-August', 'Year-round')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='family_friendly',
            field=models.BooleanField(default=False, help_text='Whether this place is suitable for families with children'),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours for each day of the week'),
        ),
        migrations.AddField(
            model_name='place',
            name='peak_season',
            field=models.CharField(blank=True, help_text="Peak tourist season (e.g., 'December-March', 'July-September')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='pet_friendly',
            field=models.BooleanField(default=False, help_text='Whether pets are allowed at this place'),
        ),
        migrations.AddField(
            model_name='place',
            name='price_range',
            field=models.CharField(choices=[('free', 'Free'), ('low', 'Low (Under KES 500)'), ('medium', 'Medium (KES 500 - 2000)'), ('high', 'High (KES 2000 - 5000)'), ('luxury', 'Luxury (Over KES 5000)')], default='free', help_text='Price range for visiting this place', max_length=20),
        ),
    ]
