# Generated by Django 4.2 on 2025-08-25 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0022_agency_certifications_agency_group_size_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('romantic', 'Romantic Date'), ('family', 'Family Day Out'), ('friends', 'Friends Hangout'), ('solo', 'Solo Adventure'), ('business', 'Business Meeting'), ('cultural', 'Cultural Experience'), ('adventure', 'Adventure/Outdoor'), ('relaxation', 'Relaxation/Wellness'), ('food', 'Food & Dining'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping Trip'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('planned_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_currency', models.CharField(default='KES', max_length=3)),
                ('group_size', models.PositiveIntegerField(default=2)),
                ('is_public', models.BooleanField(default=False, help_text='Make this plan visible to others')),
                ('allow_suggestions', models.BooleanField(default=True, help_text='Allow AI to suggest activities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date Plan',
                'verbose_name_plural': 'Date Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='agency',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, help_text='Languages spoken by staff'),
        ),
        migrations.CreateModel(
            name='DatePlanSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggested_date', models.DateField()),
                ('estimated_duration', models.PositiveIntegerField(help_text='Duration in hours')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_activities', models.JSONField(default=list, help_text='List of suggested activities')),
                ('ai_prompt', models.TextField(help_text='Original prompt used to generate suggestion')),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('user_feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date Plan Suggestion',
                'verbose_name_plural': 'Date Plan Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatePlanPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_plan_types', models.JSONField(blank=True, default=list)),
                ('preferred_activities', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_currency', models.CharField(default='KES', max_length=3)),
                ('preferred_duration', models.PositiveIntegerField(default=4, help_text='Preferred duration in hours')),
                ('group_size_preference', models.PositiveIntegerField(default=2)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('accessibility_needs', models.JSONField(blank=True, default=list)),
                ('allow_ai_suggestions', models.BooleanField(default=True)),
                ('ai_suggestion_frequency', models.CharField(choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('never', 'Never')], default='sometimes', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date Plan Preference',
                'verbose_name_plural': 'Date Plan Preferences',
            },
        ),
        migrations.CreateModel(
            name='DateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('entertainment', 'Entertainment'), ('outdoor', 'Outdoor Activities'), ('cultural', 'Cultural'), ('shopping', 'Shopping'), ('wellness', 'Wellness & Spa'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('education', 'Education & Learning'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='listings.dateplan')),
                ('related_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_activities', to='listings.agency')),
                ('related_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_activities', to='listings.place')),
            ],
            options={
                'verbose_name': 'Date Activity',
                'verbose_name_plural': 'Date Activities',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DatePlanCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('contributor', 'Contributor')], default='viewer', max_length=20)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_add_activities', models.BooleanField(default=False)),
                ('can_remove_activities', models.BooleanField(default=False)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('date_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='listings.dateplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date Plan Collaboration',
                'verbose_name_plural': 'Date Plan Collaborations',
                'unique_together': {('date_plan', 'user')},
            },
        ),
    ]
