# Generated by Django 4.2 on 2025-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_placeorder_placestaff_placeorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptours',
            name='tour_video',
            field=models.FileField(blank=True, help_text='Short video explaining the tour (MP4, MOV, AVI - max 100MB)', null=True, upload_to='tours/videos/'),
        ),
    ]
