# Generated by Django 5.2.5 on 2025-08-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_grouptours_tour_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_intro_video',
            field=models.FileField(blank=True, help_text='Short introduction video about the place (MP4, MOV, AVI - max 100MB)', null=True, upload_to='places/intro_videos/'),
        ),
    ]
