# Generated by Django 5.2.5 on 2025-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_place_place_intro_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(choices=[('travel_tours', 'Travel & Tours'), ('transport', 'Transport'), ('photo_video', 'Photo & Videography'), ('accommodation', 'Accommodation'), ('events_planners', 'Events Planners')], default='travel_tours', max_length=50),
        ),
    ]
