# Generated by Django 5.2.5 on 2025-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_alter_agency_agency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='admissionfee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text="List of specialties (e.g., ['safari', 'cultural', 'wildlife', 'beach', 'wedding', 'corporate', 'photography', 'videography', 'car_rental', 'hotel', 'lodge'])"),
        ),
    ]
